serenity.test.root=starter
serenity.take.screenshots=DISABLED
serenity.reports.show.step.details=false
headless.mode=true
webdriver.driver=provided
webdriver.provided.type=mydriver
webdriver.provided.mydriver=starter.conf.HealeniumDriver
serenity.driver.capabilities=mydriver
serenity.test.root = stepdefinitions
serenity.step.delay = 500