# Desactiva los reportes pesados que colapsan tu CPU
serenity.test.root=starter
serenity.take.screenshots=DISABLED
serenity.reports.show.step.details=false
headless.mode=true
# Esto fuerza a que use el driver que configuramos antes
webdriver.driver=provided
webdriver.provided.type=mydriver
webdriver.provided.mydriver=starter.conf.HealeniumDriver
serenity.driver.capabilities=mydriver